name: Add Issues to Project
on:
  issues:
    types: [labeled, opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write

    steps:
      - name: Check if issue has "open" label
        if: contains(github.event.issue.labels.*.name, 'open')
        run: echo "Issue has the 'open' label"

      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: "https://github.com/users/loviedo-palo/projects/1"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: "open"
